openedx/taxonomy-connector

- taxonomy/forms.py
- taxonomy/templates/taxonomy/refresh_course_skills.html
- taxonomy/urls.py
- taxonomy/views.py
- test_settings.py
- tests/test_forms.py
- tests/test_urls.py
- tests/test_views.py
Django Tool: Call API to refresh a single course's course-skill data
**Testing Scenario:**
1. Please check this PR.
2. Please Navigate to [Course Discovery Page](http://localhost:18381/admin/taxonomy/refresh_course_skills/)
3. Please enter a valid course UUID and course skills will be updated at [Course Skills](http://localhost:18381/admin/taxonomy/courseskills/)
> ENT-3375 Added Django admin page for refreshing course skills

- CHANGELOG.rst
- setup.py
- taxonomy/__init__.py
This PR makes sure that migrations and python packages are included in the final build.
> ENT-3428: Include package data, so that migrations and python packages are included in the final build.

- CHANGELOG.rst
- docs/conf.py
- requirements/dev.txt
- requirements/test.txt
- requirements/travis.txt
- setup.py
- taxonomy/__init__.py
- taxonomy/constants.py
- taxonomy/emsi_client.py
- taxonomy/exceptions.py
- taxonomy/management/commands/refresh_course_skills.py
- taxonomy/management/commands/refresh_job_postings_data.py
- taxonomy/management/commands/refresh_job_skills.py
- taxonomy/models.py
- taxonomy/urls.py
- tests/management/test_refresh_course_skills.py
- tests/management/test_refresh_job_postings_data.py
- tests/management/test_refresh_job_skills.py
- tests/test_apps.py
- tests/test_emsi_client.py
After the update of the repository name from `taxonomy-service` to `taxonomy-connector`, we also need to update all the occurrences inside the repository. This PR handles these updates.
> ENT-3372: Renamed main package name from taxonomy-service to taxonomy-connector

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/emsi_client.py
- test_settings.py
- tests/management/test_refresh_course_skills.py
- tests/management/test_refresh_job_postings_data.py
- tests/management/test_refresh_job_skills.py
- tests/test_emsi_client.py
During development, I found that sometimes connecting to EMSI Client raises `TypeError`. This is caused by the `client` attribute on EMSI Client being `None`. 
__Error Message:__
```
E           AttributeError: 'NoneType' object has no attribute 'versions'
```
> ENT-3897: Fixed TypeError that pops up sometimes while communicating with the EMSI API.

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/management/commands/refresh_course_skills.py
- taxonomy/utils.py
- tests/management/test_refresh_course_skills.py
Handled edge cases in `refresh_course_skills` command
Also removed noise from the logging.
- Each step in the release build has a condition flag that checks if the rest of the steps are …
> ENT-4202 | Handled edge cases in `refresh_course_skills` command.

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/serializers.py
- taxonomy/utils.py
- tests/test_utilities.py
> ENT-4158: Added a utility method to return serialized skills

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/utils.py
- tests/test_utilities.py
> feat: add get_course_jobs util method

- .coveragerc
- CHANGELOG.rst
- README.rst
- taxonomy/__init__.py
- taxonomy/api/urls.py
- taxonomy/api/v1/serializers.py
- taxonomy/api/v1/urls.py
- taxonomy/api/v1/views.py
- taxonomy/urls.py
> ENT-4141: Added APIs for taxonomy connector models.

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/constants.py
- taxonomy/algolia/serializers.py
- test_utils/factories.py
> WS-2162: Added a limit of 20 embedded records per job to limit records size.

- CHANGELOG.rst
- requirements/base.in
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
- taxonomy/__init__.py
- taxonomy/admin.py
- taxonomy/constants.py
- taxonomy/utils.py
- tests/management/test_refresh_course_skills.py
- tests/test_utilities.py
> Added ability for translating course description using amazon translate service

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/emsi/client.py
> FC-0001: Remove EdxRestApiClient usage in taxonomy-connector

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/signals/handlers.py
- taxonomy/signals/signals.py
[PROD-2902](https://2u-internal.atlassian.net/browse/PROD-2902)
Adds a django signal triggered by Discovery (added in https://github.com/openedx/course-discovery/pull/3539). This signal will be used to call EMSI Api to update skills for Programs.
(so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- This **must** be done after the version is visible in PyPi as `make upgrade` in course-discovery will look for the …
> feat: use program update signal to call EMSI API

- CHANGELOG.rst
- taxonomy/serializers.py
- tests/test_utilities.py
Update the skill serializer to include category and sub-category details. If either is missing, null is provided in the data. This new format is intended for use in Algolia models in discovery.
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and …
> feat: update skill serializer to include category and subcategory details

- CHANGELOG.rst
- Makefile
- taxonomy/__init__.py
- taxonomy/utils.py
- tests/test_utilities.py
This will help performance related to jobs that have to fetch a lot of the
same course data multiple times during a single run.
https://2u-internal.atlassian.net/browse/ENT-6169
* Check out this branch.
* From devstack, do `make dev.up.discovery`, make sure the elasticsearch container starts up.
* `make discovery-shell` and then `pip install -e /edx/src/taxonomy-connector` to install these changes locally in editable mode.
* (possibly) restart discovery devserver `make discovery-restart-devserver`
* Make a request to the `/search/all` endpoint, curl command copied below
```
curl --location --request POST 'http://localhost:18381/api/v1/search/all/?page_size=10' \
--header 'Authorization: JWT [your-jwt-here]' \
--header 'Content-Type: application/json' \
--data-raw '{ …
```
> feat: cache serialized course skills

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/serializers.py
- tests/algolia/test_serializers.py
> feat: Add ID of job in serializer for Algolia

- taxonomy/utils.py
- test_utils/factories.py
- tests/test_utilities.py
Refactor util method in a way that it would return program skills as well based on the product type.
PROD-2950
- Each step in the release build has a condition flag that checks if the rest …
> refactor: change util method to return program skills

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/choices.py
- taxonomy/utils.py
Fixing #109 by adding default values to the util functions.
- Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to …
> fix: add default values and bump version

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/utils.py
- tests/management/test_refresh_course_skills.py
- tests/test_utilities.py
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-6293
**Description:** We currently only use `full_description` field of a course for skill tagging but we believe that including course `title` and `short_description` fields can generate and improve course skill tagging and cover more use cases.
- *Note*: Assets will be …
> feat: Expand course skills tagging to include title, short_description and full_description.

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/utils.py
**Description:**
* Do no concatenate if short_description is None.
* Fix CourseSkills update_or_create call.
- Each step in the release build has a condition flag that checks if the rest of …
> fix: misc fixes for course skill tagging

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/serializers.py
- tests/algolia/test_utils.py
This PR adds industry names in the industry_names field in `JobSerializer` which contains the industry names in which the job belongs. The Jira ticket has decided structure of serializer. 
JIRA: [ENT-6411](https://2u-internal.atlassian.net/browse/ENT-6411)
Some of the screenshots of Algolia index with data from local database. 
Job which is not linked to any industry. 
Jobs which are linked to some industries. 
- It may or may not make a …
> Industry name in JobSkills Algolia Serializer

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/serializers.py
- tests/algolia/test_utils.py
**Description:**
Same industry name seems to be repeated multiple times for a job. This issue was introduced when the industry data was indexed in Algolia for the first time and have been like this ever since.
**Solution**
Update the query of fetching industry_names from DB in serializer and write a test case of it.
- *Note*: …
> fix: handle repeating industry names in algolia index and test

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/emsi/client.py
> ENT-6616 | fix: Added ACCESS_TOKEN_EXPIRY_THRESHOLD_IN_SECONDS in EMSI client.

- CHANGELOG.rst
- taxonomy/__init__.py
> chore: version update for ordering in SkillsQuiz viewset

- CHANGELOG.rst
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
- taxonomy/__init__.py
- taxonomy/signals/handlers.py
- taxonomy/tasks.py
- taxonomy/utils.py
- tests/test_signals.py
Adds handler to take `XBLOCK_SKILL_VERIFIED` signal from openedx-events implemented in https://github.com/open-craft/openedx-events/pull/1 and updates counts of related xblock skills.
**Related MRs**
- https://github.com/openedx/openedx-events/pull/165
- https://github.com/open-craft/xblock-skill-tagging/pull/1
**Test instructions**
- Checkout this branch. (No need for devstack, this can be tested independently)
- Create a virtual environment with python 3.8 and activate it.
- Run `make requirements` and `python manage.py migrate`.
- Open django shell using `python manage.py shell`.
- Run below piece of code
```python
import factory
import factory.fuzzy
from taxonomy import models
from test_utils.factories import *
XBlockSkillsFactory.create_batch(5) …
```
> feat: xblock verification event handler

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/management/commands/refresh_job_skills.py
JIRA: https://2u-internal.atlassian.net/browse/ENT-6919 …
> fix: Do not create a job if all of the releated skills does not exist in database

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/admin.py
__Jira Ticket:__ [ENT-6975](https://2u-internal.atlassian.net/browse/ENT-6975)
1. Delete job records that have no job skills.
2. Impact: clean the db after the bug fixed in the prior sprint, no jobs showing up in Skills Builder / other experiences that don’t have a job-skill relationships.
- *Note*: Assets …
> ENT-6975: Added the ability to remove unused jobs from django admin.

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/api/v1/views.py
- tests/test_views.py
***Description***
** Previous Implementation ***,
we are getting `sub_categories` where at least one skill is related to `current_job` in `jobSkills`. In this way, the `sub_categories` that we obtain also contain other skills that are not even related to the `current_job`.
***Current Implementation***
I filtering the skills in a `sub_category` that is only directly related to the `current_job`. In this way, the number of skills that are shown in a `sub_category` in the chart will become fewer and more relevant as compared to the previous approach, and this will reduce the false positive effect.
[JIRA ENT-6976](https://2u-internal.atlassian.net/browse/ENT-6976)
- Checkout the [Database …
> feat: making sub_category skills to job specific in career tab

- .github/workflows/ci.yml
- requirements/ci.in
- requirements/ci.txt
- requirements/dev.txt
Context: https://about.codecov.io/blog/message-regarding-the-pypi-package/
- ❌ (won't do) Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
> build: remove unnecessary codecov dependency & upgrade GHA

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/management/commands/generate_job_descriptions.py
- taxonomy/signals/handlers.py
- tests/management/test_generate_job_descriptions.py
- tests/test_models.py
**Description:** Generate job description only if a job has a name and its description is empty.
- Each step in the release build has a condition flag that checks if the rest of the steps …
> fix: generate job description only if job has name and description is empty

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/serializers.py
- tests/algolia/test_serializers.py
[APER-2377]
I am requesting an update to the data provided by the JobSerializer. We would like to limit the job options a learner can select from using the B2C version of the Skills Builder. To do this, we need an attribute in the data pushed to Algolia that we can filter on.
To do this, we have added a new derived field to the JobSerializer. It will check a new setting (`TAXONOMY_B2C_JOB_ALLOWLIST`) which is a (string) list of job ids (the lightcast `external_id`). If the external ID of a job matches an item on the list, it is "allowlisted" and can be displayed as an option to the B2C learners.
I don't think this change should affect existing consumers of this Algolia index.
Thanks for your consideration!
- `make upgrade && make requirements` have been run to …
> feat: add 'b2c_opt_in' attribute to job serializer

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/constants.py
- Updates the list of attributes that can be used on filtering. This will allow us to filter on the new attribute (`b2c_opt_in`) in the B2C Skills Builder
- Each step in the release build …
> fix: update the `attributesForFaceting` list to include the `b2c_opt_in` field

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/api/v1/urls.py
- taxonomy/api/v1/views.py
- tests/test_views.py
JIRA: [ENT-7192](https://2u-internal.atlassian.net/browse/ENT-7192)
**Context**
Previously, created this draft PR https://github.com/openedx/taxonomy-connector/pull/160 containing a management command which updates the current job of learners in extended profile of learners in LMS. During testing of this management command, found out that only the learner themselves are allowed to edit their extended profile. This check is implemented by matching the username of user calling the API with the username in user profile. This makes user privileges irrelevant. Now, I have changed the approach. Moved the database query in this API to fetch current_job data of learners and writing a management command in LMS to use this endpoint. 
- `make upgrade && make …
> feat: LearnersCurrentJobAPIView to fetch current job of learners in LMS

- CHANGELOG.rst
- taxonomy/api/filters.py
- taxonomy/api/v1/views.py
- taxonomy/exceptions.py
- taxonomy/management/commands/refresh_xblock_skills.py
- taxonomy/utils.py
- tests/management/test_refresh_xblock_skills.py
- tests/test_utilities.py
- tests/test_views.py
Adds functionality reuse tags from another xblock if the content is same, reducing calls to external API.
This PR also updates the logic to mark a course run as processed in terms of xblock tagging as well as fixes a bug with Xblock skills API where it returns duplicate skills for an xblock.
**Setup and Test instructions**
**Setup**
* Setup latest devstack master branch locally.
* Run required services using `make {lms,studio,discovery}-up`
* Open discovery shell using `make discovery-shell`.
* Install this repo using `pip install -e /edx/src/taxonomy-connector`
* Login to discovery admin at http://localhost:18381/admin/ with edx user.
* Go to http://localhost:18381/admin/taxonomy/xblockskills/ and create an XBlockSkills entry using below details:
```
Usage key: …
```
> feat: reuse tags from similar product

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/constants.py
A missing comma in the Algolia constants was preventing the b2c_opt_in attribute from being used.
- Each step in the release build has a condition flag that checks if the rest of the steps …
> fix: missing comma masking b2c_opt_in attribute

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/emsi/client.py
- tests/emsi/test_client.py
**Jira Ticket**: [ENT-7588](https://2u-internal.atlassian.net/browse/ENT-7588)
**Description**:
LightCast API was throwing errors when processing larger data sizes, handled it by adjusting data chunking to a maximum size of 50,000 bytes, aligning with LightCast's supported max data size limit.
- *Note*: Assets will be added …
> fix: chunked data in EMSI client for xblock-skills job

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/algolia/serializers.py
- taxonomy/algolia/utils.py
- taxonomy/api/v1/serializers.py
- taxonomy/utils.py
__Jira Ticket:__ [ENT-7622](https://2u-internal.atlassian.net/browse/ENT-7622)
This PR replaces all the direct usages of `JobSkills` and `IndustryJobSkill`'s `objects` with the utility methods added in `BaseJobSkill` model
- *Note*: Assets will be added automatically. You just need to provide a tag (should …
> ENT-7622: Removed direct usages objects in favour of whitelisted or blacklisted query sets.

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/utils.py
[PROD-3860](https://2u-internal.atlassian.net/browse/PROD-3860)
---------
This PR modifies prefetch queryset to select_related query to reduce db round-trip for a skill fetching.
Testing:
-------
- Clone taxonomy in `edx/src` directory.
- Install taxonomy via discovery shell in editable mode
```bash
pip install -e /edx/src/taxonomy-connector
```
- Comment cache-related code to verify the impact
- Add `Course Skills` to courses via discovery admin.
- Check query count on master and ensure the response has skills information.
- Checkout `modify-queryset` and hit the endpoint again. Note the decrease in query count.
----------
- Tested `search/all` endpoint with 2 scenarios:
Course with multiple skills -> (with no skill_category and skill_subcategory)
- with select_related: 94-96 queries
- …
> feat: modify queryset from prefetch to select related

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/utils.py
- tests/test_utilities.py
> fix: Added null safeguard before saving job description

- CHANGELOG.rst
- taxonomy/__init__.py
- taxonomy/admin.py
https://github.com/user-attachments/assets/55add20f-b373-4183-ba1e-3e1e3165507a
- Each step in the release build has a condition flag that checks if the rest of the steps …
> feat: Added a search feature on skill field in CourseSkills

- .github/workflows/ci.yml
- .github/workflows/mysql8-migrations.yml
- .github/workflows/pypi-publish.yml
This code does not have any dependencies that are specific to any specific
version of ubuntu.  So instead of testing on a specific version and then needing
to do work to keep the versions up-to-date, we switch to the ubuntu-latest
target which should be sufficient for testing purposes.
This work is being done as a part of https://github.com/openedx/platform-roadmap/issues/377
closes https://github.com/openedx/taxonomy-connector/issues/200
> build: Switch to ubuntu-latest for builds

- .github/workflows/mysql8-migrations.yml
> chore: update github actions cache from v2 to v4

- .github/workflows/upgrade-python-requirements.yml
Tested successfully here: https://github.com/openedx/taxonomy-connector/actions/workflows/upgrade-python-requirements.yml
- Each step in the release build has a condition flag that checks …
> build: fix typo in upgrade-python-requirements.yml

- CHANGELOG.rst
- taxonomy/__init__.py
Merged Requirements PR: https://github.com/openedx/taxonomy-connector/pull/220
- Each step in the release build has a condition flag that checks if the rest of the steps are …
> chore: upgrade version against python requirements

- requirements/base.in
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/test.txt
Remove unused openai pypi pkg.
(so basically once your …
> chore: remove unused openai pypi pkg
