openedx/taxonomy-connector

taxonomy/api_client/discovery.py, taxonomy/management/commands/refresh_course_skills.py, test_utils/sample_responses/skills.py, tests/management/test_refresh_course_skills.py
Description: This PR adds more tests for the refresh_course_skills management command.
JIRA: https://openedx.atlassian.net/browse/ENT-3369
=> ENT-3369: Added tests

CHANGELOG.rst, setup.py, taxonomy/__init__.py
This PR marks the first stable release for taxonomy service.
=> ENT-3428: First stable release of taxonomy

.travis.yml, requirements/base.in, requirements/constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/test.txt, requirements/travis.txt, taxonomy/exceptions.py, taxonomy/management/commands/refresh_course_skills.py, taxonomy/tasks.py, taxonomy/utils.py, taxonomy/views.py, test_settings.py, tests/management/test_refresh_course_skills.py, tests/test_tasks.py, tests/test_views.py, tox.ini
**Description:** Add a celery task to update course skills in background.
**JIRA:** [ENT-3758](https://openedx.atlassian.net/browse/ENT-3758)
=> create celery task to update course skills

taxonomy/apps.py, taxonomy/signals/handlers.py, taxonomy/signals/signals.py, taxonomy/tasks.py, tests/test_signals.py
**Description:** Add a signal and its handler to update course skills.
**JIRA:** [ENT-3758](https://openedx.atlassian.net/browse/ENT-3758)
=> Add signal and its handler to handle course skills update signal

.github/PULL_REQUEST_TEMPLATE.md, README.rst
Once this PR merged, every Taxonomy-Connector PR will have a default PR Template with a basic set of instructions and a checklist. If you feel we need more instructions here then please add those in the current branch or please write down a comment.
=> Added pull request template

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/management/commands/refresh_course_skills.py, taxonomy/utils.py, tests/management/test_refresh_course_skills.py
=> ENT-4202 | Updated logging.

CHANGELOG.rst, taxonomy/__init__.py
=> ENT-4402: Fixed .rst issues in CHANGELOG.rst

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/utils.py, tests/test_utilities.py
=> feat: add job posting data in `get_course_jobs` util

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/management/commands/refresh_job_skills.py
**JIRA:** https://openedx.atlassian.net/browse/ENT-4581 …
=> feat: Decrease skills query chunk size to fetch more jobs

CHANGELOG.rst, requirements/base.in, requirements/ci.txt, requirements/dev.txt, requirements/pip.txt, requirements/test.txt, taxonomy/__init__.py, taxonomy/constants.py, taxonomy/utils.py, tests/test_utilities.py
=> feat: added ability for translating large size text

.github/workflows/mysql8-migrations.yml, test_settings.py
build: running mysql8 migrations check.
=> build: running mysql8 migrations check.

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/utils.py
=> feat: Check the encoded course-description text size

tox.ini
=> refactor: Change the dependency file for pii_annotations

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/admin.py, taxonomy/management/commands/fetch_skill_details.py
=> ENT-5865: fix: Fixed EMSI API rate limiting issue and updated admin list_display fields.

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/management/commands/refresh_job_postings_data.py, test_utils/sample_responses/job_postings.py
=> ENT-5896: fix: Added handling for None values for median salary from EMSI.

requirements/ci.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/test.txt
- Django has released a new security patch so upgrading all edx IDAs/Services/major repos.
=> Django 3.2.15 security patch upgrade

taxonomy/__init__.py
=> feat: update version in taxonomy init

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/api/filters.py, taxonomy/api/v1/views.py, test_settings.py, tests/test_permissions.py, tests/test_views.py
=> feat: add support to filter skills by names

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/management/commands/refresh_course_skills.py, taxonomy/management/commands/refresh_program_skills.py, taxonomy/tasks.py, taxonomy/utils.py, tests/test_utilities.py
[PROD-2949](https://2u-internal.atlassian.net/browse/PROD-2949)
Fixes issues regarding hardcoded product types by replacing `ProductTypes` choices. This PR adds consistency and readability in both Taxonomy and Discovery.
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version …
=> fix: use ProductTypes choices in every util

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/api/v1/serializers.py, taxonomy/api/v1/urls.py, taxonomy/api/v1/views.py, tests/test_views.py
=> feat: Added JobTopSkillCategoriesAPIView.

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/api/v1/urls.py, taxonomy/api/v1/views.py, tests/test_views.py
=> feat: Job holder usernames API

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/algolia/constants.py
=> feat: algolia job index faceting on industry name

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/api/filters.py, taxonomy/api/v1/serializers.py, taxonomy/api/v1/urls.py, taxonomy/api/v1/views.py, test_utils/factories.py, tests/test_views.py
**Description:**
Adds api to fetch xblocks related to a skill as well as fetch skills related to an XBlock.
Original MR: https://github.com/open-craft/taxonomy-connector/pull/2
**Test instructiions**
1. Clone this repo in `<devstack_base_dir>/src/ and checkout this branch.
2. Verify tests using `make requirements validate` in repo folder.
3. Start lms and discovery service using `make lms-up discovery-up`.
4. Open discovery shell: `make discovery-shell`.
5. Install this repo using `pip install -e /src/taxonomy-connector`.
6. Run `./manage.py migrate`.
7. Run `./manage.py shell`.
8. Execute below lines to populate db with test data
```python
import factory
import factory.fuzzy
from taxonomy import models
from test_utils.factories import *
XBlockSkillsFactory.create_batch(5) …
```
=> feat: add xblocks to api

CHANGELOG.rst, requirements/base.in, requirements/ci.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/test.txt, taxonomy/__init__.py, taxonomy/algolia/serializers.py, taxonomy/algolia/utils.py, tests/algolia/test_serializers.py, tests/algolia/test_utils.py
**Description:**
Added jobs recommendations in the Algolia Jobs Index. Now every job object in Algolia Index contains a list named similar_jobs which contains at most three similar jobs. 
The screenshot of index generated through the local devstack data is
- *Note*: Assets will be added automatically. You just need to provide …
=> feat: job recommendations in algolia jobs index

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/emsi/client.py, taxonomy/management/commands/fetch_skill_details.py, taxonomy/utils.py, test_settings.py, tests/test_utilities.py
__JIRA Ticket:__ [ENT-6682](https://2u-internal.atlassian.net/browse/ENT-6682)
We need to ensure that this job completes successfully. We should catch this error and take steps to remediate. Possible solutions:
- Catch the exception and throttle our requests as necessary until the job completes
- Break the job up into smaller, daily jobs, rather than one weekly job
__Acceptance Criteria:__
1. Determine the solution for this issue, whether from the suggestions, or something new entirely
2. Implement solution
3. Monitor the fetch skills job to ensure that problem doesn’t reoccur. 
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/E …
=> ENT-6682: Added logic to avoid 429 errors and handle these errors if they still appear.

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/algolia/serializers.py, taxonomy/algolia/utils.py, tests/algolia/test_serializers.py, tests/algolia/test_utils.py
=> feat: Index industry data in Algolia

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/api/v1/serializers.py, taxonomy/api/v1/views.py
Added pagination in JobHolderUsernamesAPIView API which will be used to fetch learner current job data from course discovery to LMS.
JIRA: [ENT-7192](https://2u-internal.atlassian.net/browse/ENT-7192)
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) …
=> feat: pagination in learner JobHolderUsernamesAPIView API

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/algolia/serializers.py, taxonomy/algolia/utils.py, taxonomy/constants.py
__Jira Ticket:__ [ENT-7234](https://2u-internal.atlassian.net/browse/ENT-7234)
This PR adds a new field  in job's algolia index that will be used to filter result on the frontend side.
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and …
=> ENT-07234: Added a new field  in job's algolia index.

requirements/dev.txt, requirements/doc.txt
https://www.djangoproject.com/weblog/2023/jul/03/security-releases/
=> chore: django security patch 3.2.20 upgrade

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/algolia/utils.py
=> perf: pandas dataframe loading memory optimisation

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/algolia/constants.py, taxonomy/algolia/serializers.py, taxonomy/algolia/utils.py, tests/algolia/test_serializers.py
__Jira Ticket:__ [ENT-7294](https://2u-internal.atlassian.net/browse/ENT-7294)
Previous updates (https://github.com/openedx/taxonomy-connector/pull/172/files) fixed memory related issues but command is still taking a long time to run and fails because of that. Further debugging revealed that pagination was not correct applied while fetching jobs from the database along with some other places that needed optimization. I have made changes in those places to improve the running time of the management command.
- Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on …
=> ENT-7294: Further performance enhancements for the algolia index command.

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/algolia/constants.py, taxonomy/algolia/utils.py
__Jira Ticket:__ [ENT-7294](https://2u-internal.atlassian.net/browse/ENT-7294)
Fixed some implementation issues in job recommendation logic.
- Each step in the release …
=> fix: Fixed some implementation issues in job recommendation logic.

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/algolia/constants.py, taxonomy/algolia/utils.py
__Jira Ticket:__ [ENT-7123](https://2u-internal.atlassian.net/browse/ENT-7123)
Recently we saw that a job name `Unclassified` exists in our jobs database. This does not look like a real job. We need to review all jobs and blacklist those which doesn’t make sense.
**Acceptance Criteria:**
1. Unrealistic jobs have been blacklisted
- It may or may not make a migration depending on exactly what you modified, but it should still be …
=> ENT-7123: Added the ability to ignore unrelated jobs from being indexed on algolia.

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/utils.py, tests/test_utilities.py
To avoid the N+1 issue while fetching the catalog courses, prefetch is added to the product skills queryset so that the database access can be optimised ultimately improving the performance.
PROD-3486
- *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and …
=> feat: add prefetch related to the whitelisted product skills

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/management/commands/finalize_xblockskill_tags.py
=> feat: Optimized finalize_xblockskill_tags command for memory via chunking

CHANGELOG.rst, taxonomy/__init__.py, taxonomy/utils.py
=> fix: Fixed the transaction issue in the delete_product util function

.github/workflows/ci.yml, CHANGELOG.rst, setup.py, taxonomy/__init__.py, taxonomy/admin.py, tox.ini
- Added support for `Django 5.2` under the issue #226 
- bumped package version to `2.2.0`
=> feat: add django 5.2 support

CHANGELOG.rst, taxonomy/__init__.py
=> chore: update pkg version and changelog
